version: "3"
volumes:
  grafana:
  prometheus:

services:
  grafana:
    image: grafana/grafana 
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    
  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus:/etc/prometheus/
      - $PWD/configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  blackbox:
    image: prom/blackbox-exporter:master
    volumes:
      - $PWD/configs/:/config
    command: --config.file=/config/blackbox.yml
    ports:
      - 9115:9115

  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - 9080:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
    volumes:
      - $PWD/configs/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf

  http-dl:
    build: ./http_dl_test/.
    command: -g graphite -x docker_dl 
    restart: always

  iperf-tcp-dl:
    build: ./iperf_test/.
    command: -t 13.48.212.162 -p 5201 -d 60 -g graphite -x dl_tcp
    restart: always
