version: "3"
volumes:
  grafana:
  prometheus:

services:
  grafana:
    image: grafana/grafana 
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - 9080:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
    volumes:
      - $PWD/configs/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
