modules:
  http_2xx:
    prober: http
    timeout: 2s
    http:
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
  http_post_2xx:
    prober: http
    http:
      method: POST
  tcp_connect:
    prober: tcp
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
  icmp:
    prober: icmp
    timeout: 1s
    icmp:
      preferred_ip_protocol: ip4
